### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by prankyboy** [nekudo/com_wemahu#1]
Hello
I want to use com wemahu to try to solve a probable malware issue on a site.
Please, to install it i have to upload it in the temp folder?
thx

**Comment by nekudo** [comment]
First: Please note that this component is no longer maintained. See: https://nekudo.com/blog/wemahu-discontinued

If you still want to use it, i attached an installable version for joomla.

[com_wemahu_v1.0.3.zip](https://github.com/nekudo/com_wemahu/files/65088/com_wemahu_v1.0.3.zip)

**Comment by prankyboy** [comment]
thx SimonI know that is out of date but I try to understand if 404javascript.js is a malware

```
Il Giovedì 17 Dicembre 2015 8:55, Simon Samtleben <notifications@github.com> ha scritto:
```

 First: Please note that this component is no longer maintained. See: https://nekudo.com/blog/wemahu-discontinuedIf you still want to use it, i attached an installable version for joomla.com_wemahu_v1.0.3.zip—
